version: '3.8'

services:
  backend:
    platform: linux/amd64
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    volumes:
      - ./backend:/app
    networks:
      - app-network

  frontend:
    platform: linux/amd64
    build:
      context: ./frontend_old
      dockerfile: Dockerfile
    ports:
      - "9099:9099"
    environment:
      - PORT=9099
    volumes:
      - ./frontend_old:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
