"""NCSS-aligned taxonomy helpers: term lookup, legacy-alias normalisation, age bands and NCSS parents.

Data comes from taxonomy_data.json, generated by scripts/ncss_eval/export_taxonomy.py. This file is vendored byte-for-byte
into functions/new_scheme/taxonomy.py (separate deploy unit); tests/unit/test_taxonomy_sync.py keeps the copies identical.
Standard library only, so it imports the same way in Cloud Run and Firebase Functions.
"""

import json
import logging
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Set, Tuple

logger = logging.getLogger(__name__)

TAXONOMY = json.loads((Path(__file__).parent / "taxonomy_data.json").read_text())
FIELDS = ("who_is_it_for", "what_it_gives", "scheme_type")
_PARENT_KEY = {"who_is_it_for": ("age_group", "profile"), "what_it_gives": ("intervention",), "scheme_type": ("need",)}

_TERMS: Dict[str, Dict[str, dict]] = {f: {t["name"]: t for t in TAXONOMY[f]} for f in FIELDS}
_LOWER: Dict[str, Dict[str, str]] = {f: {n.lower(): n for n in _TERMS[f]} for f in FIELDS}
_RENAMES_LOWER = {old.lower(): new for old, new in TAXONOMY["renames"].items()}
_ALIASES_LOWER = {f: {old.lower(): v for old, v in TAXONOMY["legacy_aliases"].get(f, {}).items()} for f in FIELDS}


def term_names(field: str) -> List[str]:
    return list(_TERMS[field])


def normalize_terms(field: str, values: Optional[Iterable[str]]) -> Tuple[List[str], List[str]]:
    """Map raw tag values to current vocabulary terms. Fails closed: no fuzzy or keyword matching.

    Order: exact (case-insensitive) -> rename -> legacy same-field alias. Returns (matched, unmatched).
    Terms an alias moves to another field, or drops, are reported as unmatched for this field; use translate_legacy
    when a whole document is being converted.
    """
    matched: List[str] = []
    unmatched: List[str] = []
    for raw in values or []:
        key = str(raw).strip().lower()
        hit = _LOWER[field].get(key)
        if hit is None and key in _RENAMES_LOWER and _RENAMES_LOWER[key] in _TERMS[field]:
            hit = _RENAMES_LOWER[key]
        if hit is not None:
            matched.append(hit)
            continue
        alias = _ALIASES_LOWER[field].get(key)
        if alias and alias.get("to"):
            matched.extend(alias["to"])
            continue
        unmatched.append(str(raw))
    if unmatched:
        logger.warning("Unmatched %s values dropped: %s", field, unmatched)
    return list(dict.fromkeys(matched)), unmatched


def translate_legacy(doc: Dict[str, Optional[List[str]]]) -> Dict[str, List[str]]:
    """Convert a document's old-vocabulary tags to the current vocabulary (renames, merges, splits, cross-field moves).

    Pure function: does not write anywhere. Values with no mapping are dropped and logged by normalize_terms.
    """
    out: Dict[str, List[str]] = {f: [] for f in FIELDS}
    for field in FIELDS:
        for raw in doc.get(field) or []:
            key = str(raw).strip().lower()
            alias = _ALIASES_LOWER[field].get(key)
            if alias and alias.get("moved"):
                for target_field, terms in alias["moved"].items():
                    out[target_field].extend(terms)
                continue
            matched, _ = normalize_terms(field, [raw])
            out[field].extend(matched)
    return {f: list(dict.fromkeys(v)) for f, v in out.items()}


def age_terms(age_min: Optional[int], age_max: Optional[int]) -> Optional[Set[str]]:
    """Age-band terms whose band overlaps [age_min, age_max] (None bounds are open). None when no age is stated."""
    if age_min is None and age_max is None:
        return None
    lo = 0 if age_min is None else age_min
    hi = 200 if age_max is None else age_max
    return {b["term"] for b in TAXONOMY["age_bands"] if lo <= b["max"] and hi >= b["min"]}


def apply_age_terms(who: Iterable[str], age_min: Optional[int], age_max: Optional[int]) -> List[str]:
    """Replace model-picked age-band terms with the bands derived in code from the stated age range.

    No age stated: keep the model's terms. Open-ended 'N and above' below 60 implies Seniors only if the model chose it.
    """
    who = list(who)
    derived = age_terms(age_min, age_max)
    if derived is None:
        return who
    if age_max is None and (age_min is None or age_min < 60):
        derived = derived | {"Seniors"} if "Seniors" in who else derived - {"Seniors"}
    band_names = {b["term"] for b in TAXONOMY["age_bands"]}
    kept = [t for t in who if t not in band_names]
    return kept + sorted(derived, key=[b["term"] for b in TAXONOMY["age_bands"]].index)


def parents(field: str, terms: Iterable[str]) -> Dict[str, List[str]]:
    """NCSS parent labels for the given terms, from the static table (never from the LLM)."""
    out: Dict[str, Set[str]] = {k: set() for k in _PARENT_KEY[field]}
    for name in terms:
        term = _TERMS[field].get(name)
        if term:
            for k in _PARENT_KEY[field]:
                out[k].update(term[k])
    return {k: sorted(v) for k, v in out.items()}


def is_provisional(field: str, name: str) -> bool:
    term = _TERMS[field].get(name)
    return bool(term and term["provisional"])
