name: Deploy to DEV

on:
  push:
    branches:
      - stg
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Set up Node.js environment
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 19.7.0

      # Step 4: Create Service Account Key
      - name: Create SA key
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SCHEMESSG_V3_DEV }}' > $HOME/gcloud.json

      # Step 5: Deploy Cloud Functions
      - name: Deploy Cloud Functions
        working-directory: backend/functions
        run: |
          python3.10 -m venv venv
          . venv/bin/activate
          npx firebase-tools --version
          python3.10 -m pip install -r requirements.txt
          export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud.json
          npx firebase-tools deploy --only functions --debug
