name: Deploy Firebase Functions

on:
  push:
    branches:
      - stg
  workflow_dispatch:

env:
  FIREBASE_PROJECT_ID: "schemessg-v3-dev"
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_SCHEMESSG_V3_DEV }}

jobs:
  deploy:
    name: Deploy Functions
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    # Step 3: Install Firebase CLI
    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    # Step 4: Install Python Dependencies
    - name: Install Dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --no-cache-dir -r functions/requirements.txt
      working-directory: ./backend

    # Step 5: Deploy Firebase Functions
    - name: Deploy Firebase Functions
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_SCHEMESSG_V3_DEV }}
      run: |
        firebase deploy --only functions --project $FIREBASE_PROJECT_ID
      working-directory: ./backend
