name: Deploy to Firebase Functions

on:
  push:
    branches:
      - stg
  workflow_dispatch:

env:
  FIREBASE_PROJECT_ID: "schemessg-v3-dev"
  SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SCHEMESSG_V3_DEV }}

jobs:
  deploy:
    name: Deploy Functions
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Set up Node.js environment
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # Step 3: Install Dependencies
    - name: Install Dependencies
      run: |
        npm install -g firebase-tools@13.25.0

    # Step 4: Authenticate Firebase CLI
    - name: Authenticate Firebase CLI
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${HOME}/serviceAccountKey.json
      run: |
        echo "$SERVICE_ACCOUNT_KEY" > ${HOME}/serviceAccountKey.json

    # Step 5: Deploy All Functions
    - name: Deploy Firebase Functions
      run: |
        firebase deploy --only functions --project $FIREBASE_PROJECT_ID
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${HOME}/serviceAccountKey.json
